## Theme
include theme.conf

## Font
font_size        19
font_family      family='CaskaydiaCove Nerd Font Mono' postscript_name=CaskaydiaCoveNFM-SemiLight
bold_font        family='CaskaydiaCove Nerd Font Mono' style=SemiLight
italic_font      auto
bold_italic_font family='CaskaydiaCove Nerd Font Mono' style='SemiLight Italic'

## Line height
modify_font cell_height 12px

## Tabs
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2
tab_powerline_style slanted

active_tab_font_style italic 
inactive_tab_font_style normal

## MacOS
macos_titlebar_color               light
macos_quit_when_last_window_closed yes

## Window
remember_window_size yes

# top, right, bottom, left
# window_margin_width  0 
# window_padding_width 0

single_window_margin_width  0 4 0 4 
single_window_padding_width 0 

## Others
copy_on_select clipboard
