## Theme
include tokyonight-moon.conf

## Font
font_size 20 
 
## Font styles
#font_family      family='CaskaydiaCove Nerd Font Mono' postscript_name=CaskaydiaCoveNFM-Regular
#bold_font        family='CaskaydiaCove Nerd Font Mono' style=Regular
#bold_italic_font family='CaskaydiaCove Nerd Font Mono' style=Italic
font_family      family='CaskaydiaCove Nerd Font Mono' postscript_name=CaskaydiaCoveNFM-Light
bold_font        family='CaskaydiaCove Nerd Font Mono' style=Light
bold_italic_font family='CaskaydiaCove Nerd Font Mono' style=LightItalic
italic_font      auto

## Line height
modify_font cell_height 9px

## Tabs
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 2
tab_powerline_style slanted

active_tab_font_style italic 
inactive_tab_font_style normal

## MacOS
macos_quit_when_last_window_closed yes

## Others
copy_on_select clipboard

window_padding_width 6
