## Theme
include monokai-pro-filter-machine.conf

## Font
font_size        17
font_family      family='CaskaydiaCove Nerd Font Mono' postscript_name=CaskaydiaCoveNFM-Regular
bold_font        family='CaskaydiaCove Nerd Font Mono' style=Regular
italic_font      auto
bold_italic_font family='CaskaydiaCove Nerd Font Mono' style=Italic

## Line height
modify_font cell_height 9px

## MacOS
macos_titlebar_color               dark
macos_quit_when_last_window_closed yes

## Tabs
tab_bar_edge        top
tab_bar_style       powerline
tab_bar_min_tabs    1
tab_powerline_style slanted

# active_tab_foreground #f2fffc
# active_tab_background #1d2528
# active_tab_font_style   italic

# inactive_tab_foreground #b8c4c3
# inactive_tab_background #1d2528
# inactive_tab_font_style   italic

## Window
remember_window_size    yes
hide_window_decorations titlebar-only

### top, right, bottom and left.
# window_border_width  4px
# window_margin_width  4 2
# window_padding_width 8 4

### top, right, bottom and left.
# single_window_margin_width  5 11 5 12
# single_window_padding_width -1

## Others
copy_on_select clipboard
enabled_layouts Horizontal, *
