# Set true color
set -g default-terminal "${TERM}"
set -ag terminal-overrides ",xterm*:Tc"

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Add mouse support
set -g mouse on

# Set split window commands
unbind %
bind \\ split-window -h
unbind '"'
bind - split-window -v

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"

# This should always be the last line.
run "~/.tmux/plugins/tpm/tpm"
