# Set true color
set -g default-terminal "${TERM}"
set -ag terminal-overrides ",xterm*:Tc"

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Add mouse support
set -g mouse on

# Set split window commands
unbind %
bind \\ split-window -h
unbind '"'
bind - split-window -v

# Navigate between windows with `Shift Opt vim keys`
bind -n M-H previous-window
bind -n M-L next-window

# Start windows and panes at index 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"

set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme storm
set -g @tokyo-night-tmux_show_git 0
set -g @tokyo-night-tmux_window_id_style none
set -g @tokyo-night-tmux_window_tidy_icons 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative 

# This should always be the last line.
run "~/.tmux/plugins/tpm/tpm"
